server:
    port: 8081
spring:
    datasource:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/drools?useUnicode:true&characterEncoding:utf-8&autoReconnect:true&useSSL:false&noAccessToProcedureBodies:true
            username: root
            password: root
            type: com.alibaba.druid.pool.DruidDataSource
            initialSize: 5
            minIdle: 5
            maxActive: 50
            maxWait: 1000
            filters: stat,wall,log4j

    redis:
            # Redis数据库索引（默认为0）
            database: 0
            # Redis服务器地址
            host: 127.0.0.1
            # Redis服务器连接端口
            port: 6379
            # Redis服务器连接密码（默认为空）
            password: 
            # 连接池最大连接数（使用负值表示没有限制）
            pool.max-active: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            pool.max-wait: -1
            # 连接池中的最大空闲连接
            pool.max-idle: 8
            # 连接池中的最小空闲连接
            pool.min-idle: 0
            # 连接超时时间（毫秒）
            timeout: 0

logging:
    level:
            com.liuzhe.drools.dao: DEBUG

